version: "3.8"
services:
  # 쓰기 전용 데이터베이스
  postgresql-main:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - postgresql_main_data:/bitnami/postgresql
      - ./replication-user-grant.sql:/docker-entrypoint-initdb. d/db.sql
    environment:
      - POSTGRESQL_REPLICATION_MODE=master              # 복제 모드 [master / slave]
      - POSTGRESQL_REPLICATION_USER=repl_user           # 복제 사용자 이름
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password   # 복제 사용자 비밀번호
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=ourhour

  # 읽기 전용 데이터베이스
  postgresql-standby:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5433:5432'
    restart: on-failure
    depends_on:
      - postgresql-main
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave               # 복제 모드 [master / slave]
      - POSTGRESQL_REPLICATION_USER=repl_user           # 복제 사용자 이름
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password   # 복제 사용자 비밀번호
      - POSTGRESQL_MASTER_HOST=postgresql-main
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password

volumes:
  postgresql_main_data:
    driver: local

