spring:
  config:
    activate:
      on-profile: dev

  docker:
    compose:
      file: docker-compose-dev.yml

  datasource:
    main:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/ourhour
        username: my_user
        password: my_password
    standby:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5433/ourhour
        username: my_user
        password: my_password


