spring:
  profiles:
    default: ${SPRING_ACTIVE_PROFILE}
    group:
      dev:
        - oauth-dev
        - db-dev

springdoc:
  swagger-ui:
    url: /docs/openapi3.yaml
    path: /swagger
    csrf:
      enabled: true

jwt:
  secret: ${SECRET}
  token-validity-time: ${TOKEN_VALIDITY_TIME}

server:
  port: 8000





