spring:
  profiles:
    default: ${SPRING_ACTIVE_PROFILE}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

springdoc:
  swagger-ui:
    url: /docs/openapi3.yaml
    path: /swagger