spring:
  config:
    activate:
      on-profile: dev

  docker:
    compose:
      file: docker-compose-dev.yml

  datasource:
    main:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/ourhour
        username: my_user
        password: my_password
    standby:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5433/ourhour
        username: my_user
        password: my_password

server:
  ssl:
    key-store: classpath:localhost.p12
    key-store-type: PKCS12
    key-store-password: changeit
  port: 8000


