spring:
  config:
    activate:
      on-profile: dev

  docker:
    compose:
      file: docker-compose-dev.yml

server:
  ssl:
    key-store: classpath:localhost.p12
    key-store-type: PKCS12
    key-store-password: changeit

