spring:
  profiles:
    default: ${SPRING_ACTIVE_PROFILE}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: postgresql

springdoc:
  swagger-ui:
    url: /docs/openapi3.yaml
    path: /swagger
    csrf:
      enabled: true

jwt:
  secret: ${SECRET}
  token-validity-time: ${TOKEN_VALIDITY_TIME}
